### ISSUE TITLE
Errors when using "npm start"

### ISSUE THREAD

**Issue by ht89** [froko/ng2-structure-sample#1]
Dear Patrick,
How are you? My name is Hung who's working at BBV Vietnam. Would you please help with the errors as shown in the link below. Thank you. Kind regards.
[errors](https://drive.google.com/open?id=0B9u9zOr_rlF8STdLNXNTRFdyRzg)

**Comment by froko** [comment]
Hi Hung

I could reproduce your issue. Webpack has been upgraded to version 2.1.0-beta.26 over the weekend. This new version doesn't allow omitting the -loader suffix in the webapack  config files anymore. I've pushed a fix for this issue in this repository and will update the other repositories during today.

**Comment by ht89** [comment]
Dear Patrick,
Thank you so much for your quick help. Kind regards.
